### PR TITLE
feat: Put methods ACK and Nack in Public Class

### PR DESCRIPTION
**Pull request by gustavodecarlo**
Hi Pedro and Krishna,

See this pull request. I followed in e-mail and comment again I cannot this this solution. But you can evaluate if you have this in mind of solution.

Thanks,

Gustavo Decarlo

### CODE REVIEW

**Comment by gustavodecarlo** [comment]
Hi Pedro,

Any problem with this suggestion of solution?

Thanks.

**Comment by krishna-kashyap** [comment]
> Hi Pedro,
> 
> Any problem with this suggestion of solution?
> 
> Thanks.

Given the extra lines added, coverage has gone down, which isn't much of a concern I guess.

We will need to clean this up without which the app devs may not be able to use the public interface, given the server may reject any sort of client side acknowledgement (ACK or NACK) once the message-id has already been acknowledged.

Could you make these changes as well please?
We may need to update the documentation as well to show how ACK/NACK needs to be used

`Lines 363 to 369 in the aiostomp module
 
        result = await subscription.handler(frame, frame.body)

        if subscription.ack in ['client', 'client-individual']:
            if result:
                self.ack(frame)
            else:
                self.nack(frame)
`

**Comment by gustavodecarlo** [comment]
Hi Krishina,

I will look into this and get back. You think we need to modify this lines
in lib to use the public method or protocol method? And put in readme doc
how to use the methods? I think the automatic control in handler function
are great, but for a specific error treatment have the methods in hand to
notify the with NACK.

Sorry if I said any nonsense.

Thanks.



Gustavo Decarlo
Skype: gustavo.secchim
Hangout: gustavodecarlo@gmail.com
Twitter: @gustavodecarlo

**Comment by krishna-kashyap** [comment]
Couple of things

1. There would be double ack or Nack since irrespective of what happens in the handler, the library will try to send an acknowledgement unless there's an exception raised. This may not be treated rightly by the server. Also here it maybe noted that ack mode set to client is to reduce the number of acks by having some sort of single ack for multiple messages, which is very hard for the library to get it right, since it's so application dependent!

2. In line with ethos of python, it's usually better when we have just one way of doing something. We could always add a context manager if you'd like as helper code for those who'd like to continue using the ack from library end

**Pull request closed without merging**
