### PR TITLE
Modified the frame parsing to support Null octets (EOF) in the body

### PR DESCRIPTION
**Pull request by krishna-kashyap**
Hi,

I hit another error when the body contained null bytes in binary. Modified the parsing of the frame to allow for parsing of such body in the frames in accordance with the protocol.

Also made a small optimization using a intermediate frame avoiding parsing the same data again and again

### CODE REVIEW

**Comment by pedrokiefer** [comment]
Great catch! Thanks for the PR!

Can you just add a test case with a null octet on the body?

**Comment by krishna-kashyap** [comment]
I'll add to the commit, sorry the file got left :(

**Comment by pedrokiefer** [comment]
Thanks!
I'll do a release shortly.

**Comment by pedrokiefer** [comment]
Released version 1.4.0 with this fix.

**Comment by krishna-kashyap** [comment]
Thanks a ton again!

**Pull request merged**
